# Seven segment LED display

set_property PACKAGE_PIN W7 [get_ports {o_seven_segments[7]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[7]}]
set_property PACKAGE_PIN W6 [get_ports {o_seven_segments[6]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[6]}]
set_property PACKAGE_PIN U8 [get_ports {o_seven_segments[5]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[5]}]
set_property PACKAGE_PIN V8 [get_ports {o_seven_segments[4]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[4]}]
set_property PACKAGE_PIN U5 [get_ports {o_seven_segments[3]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[3]}]
set_property PACKAGE_PIN V5 [get_ports {o_seven_segments[2]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[2]}]
set_property PACKAGE_PIN U7 [get_ports {o_seven_segments[1]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[1]}]
set_property PACKAGE_PIN V7 [get_ports {o_seven_segments[0]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_seven_segments[0]}]

set_property PACKAGE_PIN U2 [get_ports {o_anode_pins[0]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_anode_pins[0]}]
set_property PACKAGE_PIN U4 [get_ports {o_anode_pins[1]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_anode_pins[1]}]
set_property PACKAGE_PIN V4 [get_ports {o_anode_pins[2]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_anode_pins[2]}]
set_property PACKAGE_PIN W4 [get_ports {o_anode_pins[3]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {o_anode_pins[3]}]